language: 
  - c
  - cxx

matrix:
    include:
        - os: osx
          addons:
            homebrew:
              packges:
                - libedit
          env:
            - PKG_CONFIG_PATH="/usr/local/opt/libedit/lib/pkgconfig"
          script:
            - cd ${TRAVIS_BUILD_DIR}
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build .
            - cat ../run.txt | ./nui/nui

        - os: windows
          script:
            - cd ${TRAVIS_BUILD_DIR}
            - mkdir build
            - cd build
            - cmake -G "Visual Studio 15 2017" ..
            - cmake --build .
            - cat ../run.txt | ./nui/nui
install:
  - cd ..
  - git clone -b development https://github.com/mbrazeau/mpl.git
  - git clone -b dev https://github.com/mbrazeau/nui.git
  - git clone https://github.com/cdesjardins/ncl_mtholder.git
  - mv ncl_mtholder ./ncl
  - cd ncl
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target install
  - cd ${TRAVIS_BUILD_DIR}/..
  - mkdir external
  - cd external
  - git clone https://github.com/cdesjardins/wineditline.git

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
