language: 
  - c
  - cxx

os: 
  - windows
  - osx

install:
  - mkdir ~/bin
  - PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - repo init -u https://github.com/mbrazeau/morphyManifest.git

script:
  - cd ${TRAVIS_BUILD_DIR}
  - repo sync
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/nui

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
