language: 
  - c
  - cxx

matrix:
    include:
        - os: osx
          addons:
            homebrew:
              packges:
                - libedit
          env:
            - PKG_CONFIG_PATH="/usr/local/opt/libedit/lib/pkgconfig"

        - os: windows
          env:
            - export MAKE=mingw32-make

install:
  - cd ${TRAVIS_BUILD_DIR}
  - git clone -b development https://github.com/mbrazeau/mpl.git
  - git clone -b dev https://github.com/mbrazeau/nui.git
  - git clone  https://github.com/mbrazeau/build.git
  - git clone https://github.com/cdesjardins/ncl_mtholder.git
  - mv ncl_mtholder ./ncl
  - cd ncl
  - mkdir build
  - cd build
  - cmake ..
  - MAKE
  - MAKE install
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir external
  - cd external
  - git clone https://github.com/cdesjardins/wineditline.git

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ls
  - cd build
  - mkdir build
  - cmake .
  - MAKE
  - cat run.txt | ./build/nui/nui

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
