language: 
  - c
  - cxx

matrix:
    include:
        - os: osx
          addons:
            homebrew:
              packges:
                - libedit
          env:
            - PKG_CONFIG_PATH="/usr/local/opt/libedit/lib/pkgconfig"
            - SHELL=bash
        - os: windows
          env:
            - SHELL=sh


install:
  - git clone -b development https://github.com/mbrazeau/mpl.git
  - git clone -b dev https://github.com/mbrazeau/nui.git
  - git clone  https://github.com/mbrazeau/build.git
  - git clone https://github.com/cdesjardins/ncl.git
  - cd ncl
  - ${SHELL} bootstrap.sh
  - mkdir build
  - cd build
  - ../configure
  - make -j4
  - make
  - make install
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir external
  - cd external
  - git clone https://github.com/cdesjardins/wineditline.git

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ls
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/nui

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
