language: 
  - c
  - cxx

os: 
  - windows
  - osx

install:

script:
  - cd ${TRAVIS_BUILD_DIR}
  - repo init -u https://github.com/mbrazeau/morphyManifest
  - repo sync
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/nui

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
