language: 
  - c
  - cxx

os: 
  - windows
  - osx

install:
  - 
  - git clone -b development https://github.com/mbrazeau/mpl.git
  - git clone -b dev https://github.com/mbrazeau/nui.git
  - git clone  https://github.com/mbrazeau/build.git
  - git clone https://github.com/cdesjardins/ncl.git
  - mkdir external
  - cd external
  - git clone https://github.com/cdesjardins/wineditline.git

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ls
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/nui

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
